site_name: Geoterminal
site_description: A Python library for geospatial data processing and H3 operations
site_author: Jeronimo Luza
repo_url: https://github.com/jeronimoluza/geoterminal

theme:
  name: readthedocs
  palette:
    primary: teal
    accent: deep orange
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - toc.integrate

nav:
  - Home: index.md
  - Getting Started:
    - Installation: installation.md
    - Usage Guide: usage.md
    - CLI Reference: cli.md
  - API Reference:
    - Overview: api.md
    - Geometry Operations: api/geometry_operations.md
    - H3 Operations: api/h3_operations.md
    - File I/O: api/file_io.md
  - Contributing: contributing.md
  - FAQ: faq.md
  - Changelog: changelog.md

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [geoterminal]
          options:
            show_source: true
            show_root_heading: true
            show_object_full_path: true
            show_category_heading: true
